# Generated by Django 3.0.5 on 2020-12-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_usereat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEat',
        ),
    ]
