# Generated by Django 3.0.5 on 2020-12-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_usereat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereat',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='usereat',
            name='user',
        ),
        migrations.DeleteModel(
            name='menuInfo',
        ),
        migrations.DeleteModel(
            name='UserEat',
        ),
    ]
