# Generated by Django 3.0.5 on 2020-12-20 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0018_delete_menuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=255, null=True)),
                ('kana_name', models.CharField(max_length=255, null=True)),
                ('jp_name', models.CharField(max_length=255, null=True)),
                ('one_point', models.FloatField()),
                ('two_point', models.FloatField()),
                ('three_point', models.FloatField()),
                ('four_point', models.FloatField()),
                ('kcal', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='media/menu')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='infouser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
