# Generated by Django 3.0.5 on 2020-12-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20201220_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='foodstuff',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='usereat',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='usereat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Foodstuff',
        ),
        migrations.DeleteModel(
            name='MenuInfo',
        ),
        migrations.DeleteModel(
            name='MyRecipe',
        ),
        migrations.DeleteModel(
            name='UserEat',
        ),
    ]
