# Generated by Django 3.0.5 on 2020-12-20 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0022_auto_20201220_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('one_point_gram', models.FloatField()),
                ('one_point', models.FloatField()),
                ('two_point', models.FloatField()),
                ('three_point', models.FloatField()),
                ('four_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=255, null=True)),
                ('kana_name', models.CharField(max_length=255, null=True)),
                ('jp_name', models.CharField(max_length=255, null=True)),
                ('one_point', models.FloatField()),
                ('two_point', models.FloatField()),
                ('three_point', models.FloatField()),
                ('four_point', models.FloatField()),
                ('kcal', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='media/menu')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infouser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatTime', models.IntegerField(choices=[(1, '朝食'), (2, '昼食'), (3, '夕食'), (4, '間食')])),
                ('date', models.DateField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatmenu', to='menu.MenuInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram', models.FloatField()),
                ('foodstuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipestuff', to='menu.Foodstuff')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipemenu', to='menu.MenuInfo')),
            ],
        ),
    ]
