# Generated by Django 3.0.5 on 2020-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_auto_20201220_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodstuff',
            old_name='name',
            new_name='jp_name',
        ),
        migrations.RemoveField(
            model_name='foodstuff',
            name='four_point',
        ),
        migrations.RemoveField(
            model_name='foodstuff',
            name='one_point',
        ),
        migrations.RemoveField(
            model_name='foodstuff',
            name='three_point',
        ),
        migrations.RemoveField(
            model_name='foodstuff',
            name='two_point',
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='kana_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='point_category',
            field=models.IntegerField(choices=[(1, '1群'), (2, '2群'), (3, '3群'), (4, '4群')], null=True),
        ),
    ]
