# Generated by Django 3.0.5 on 2020-12-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_usereat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereat',
            name='menu',
        ),
        migrations.DeleteModel(
            name='menuInfo',
        ),
    ]
