# Generated by Django 3.0.5 on 2020-12-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_auto_20201217_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onePoint', models.FloatField()),
                ('twoPoint', models.FloatField()),
                ('treePoint', models.FloatField()),
                ('fourPoint', models.FloatField()),
                ('kcal', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserEat',
        ),
    ]
