# Generated by Django 3.0.5 on 2020-12-20 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0012_auto_20201220_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='media/menu'),
        ),
        migrations.AlterField(
            model_name='usereat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
