# Generated by Django 3.0.5 on 2020-12-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20201220_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuInfo',
        ),
    ]
