# Generated by Django 3.0.7 on 2020-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201116_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_level',
            field=models.IntegerField(choices=[(1, '運動レベル1'), (2, '運動レベル2'), (3, '運動レベル3')], default=3),
        ),
    ]
