# Generated by Django 3.0.5 on 2020-12-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201217_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kcal_id',
            new_name='kcal',
        ),
    ]
