# Generated by Django 3.0.5 on 2020-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_kcalinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcalinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
