# Generated by Django 3.0.5 on 2020-12-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20201218_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kcal',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentication.kcalInfo'),
        ),
    ]
