# Generated by Django 3.0.5 on 2020-12-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='kcalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_level', models.IntegerField()),
                ('age', models.IntegerField()),
                ('one_point', models.FloatField()),
                ('two_point', models.FloatField()),
                ('three_point', models.FloatField()),
                ('four_point', models.FloatField()),
                ('kcal', models.FloatField()),
            ],
            options={
                'db_table': 'kcalInfo',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='kcal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.kcalInfo'),
        ),
    ]
