# Generated by Django 3.0.5 on 2020-12-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201217_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kcal',
        ),
    ]
